// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type Article struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type ArticleInput struct {
	Name string `json:"name"`
}

type User struct {
	ID          string     `json:"id"`
	Email       string     `json:"email"`
	UserID      *string    `json:"userId"`
	Name        *string    `json:"name"`
	FirstName   *string    `json:"firstName"`
	LastName    *string    `json:"lastName"`
	NickName    *string    `json:"nickName"`
	Description *string    `json:"description"`
	Location    *string    `json:"location"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   *time.Time `json:"updatedAt"`
	Password    *string    `json:"password"`
}

type UserAuth struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserInput struct {
	Email       *string `json:"email"`
	UserID      *string `json:"userId"`
	DisplayName *string `json:"displayName"`
	Name        *string `json:"name"`
	FirstName   *string `json:"firstName"`
	LastName    *string `json:"lastName"`
	NickName    *string `json:"nickName"`
	Description *string `json:"description"`
	Location    *string `json:"location"`
	Password    string  `json:"password"`
}

type Users struct {
	Count *int    `json:"count"`
	List  []*User `json:"list"`
}
