// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type ArticleInput struct {
	Name string `json:"name"`
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Email *string `json:"email"`
}
